### ISSUE TITLE
iOS demo无法编译

### ISSUE THREAD

**Issue by gefei-li** [ymm-tech/thresh#4]
### Xcode 12.1  Release模式提示

![image](https://user-images.githubusercontent.com/7801581/103620811-1f4c7280-4f6f-11eb-99b3-16e4bd756f2a.png)

PhaseScriptExecution Run\ Script /Users/aaa/Library/Developer/Xcode/DerivedData/Runner-akiikoxwioukyebydogbsvowwiws/Build/Intermediates.noindex/Runner.build/Release-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
...
...
...
Target aot_assembly_release failed: Exception: Unsupported iOS arch name "i386"
build failed.
Command /bin/sh failed with exit code 1

### Debug模式 ，提示如下

![image](https://user-images.githubusercontent.com/7801581/103620372-51a9a000-4f6e-11eb-83d9-812b9fd0a401.png)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ThreshViewController", referenced from:
      objc-class-ref in SettingViewController.o
  "_OBJC_CLASS_$_ThreshPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_SqflitePlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_FLTPathProviderPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_ThreshAppDelegate", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### 求助该如何解决

**Comment by gefei-li** [comment]
补充环境及操作步骤 
Flutter 1.17.5

1修改yaml  cache_network_image 2.0.0-rc，否则flutter编译不过（Flutter版本过高）
2安装和更新flutter依赖，并执行flutter run。这个已经跑起来了。
![image](https://user-images.githubusercontent.com/7801581/103625429-ef549d80-4f75-11eb-806d-9cb1da3d38ef.png)

3到ios demo目录，pod install，然后修改scheme为debug或维持Release，报以上错误。

**Comment by SeaShrimper** [comment]
Sorry，the current version only supports flutter 1.9.1-hotfix.6.
Q1 2021, we plan to adapt the high version internally and will update it in time after completion.

**Comment by SeaShrimper** [comment]
Sorry，the current version only supports flutter 1.9.1-hotfix.6.
Q1 2021, we plan to adapt the high version internally and will update it in time after completion.
