### ISSUE TITLE
iOS demo一直白屏

### ISSUE THREAD

**Issue by quzhengping** [ymm-tech/thresh#6]

**Comment by JD-Tang** [comment]
麻烦贴下环境信息（flutter版本、dart版本、真机或者模拟器系统版本）

**Comment by quzhengping** [comment]
您好已经解决 问题是由于之前flutter版本是最新的，强制降级导致。如果有小伙伴遇到 可以重新进行一次flutter build ios进行重新生成 这样iOS可以就没问题了；
