### ISSUE TITLE
是否可以通过dart ffi减少通信成本?

### ISSUE THREAD

**Issue by MIFind** [ymm-tech/thresh#7]
是否可以通过[Dart VM FFI](https://flutter.dev/docs/development/platform-integration/c-interop) 减少通信成本，去掉Platform Channel，js engine - c++ - dart

**Comment by SeaShrimper** [comment]
> 是否可以通过[Dart VM FFI](https://flutter.dev/docs/development/platform-integration/c-interop) 减少通信成本，去掉Platform Channel，js engine - c++ - dart

感谢您的建议，这块确实是一个瓶颈，ffi的通信方案我们在调研做了，有兴趣的话加入我们官方群可以一起共建thresh！

**Comment by MIFind** [comment]
好滴，期待~

**Comment by MIFind** [comment]
> > 是否可以通过[Dart VM FFI](https://flutter.dev/docs/development/platform-integration/c-interop) 减少通信成本，去掉Platform Channel，js engine - c++ - dart
> 
> 感谢您的建议，这块确实是一个瓶颈，ffi的通信方案我们在调研做了，有兴趣的话加入我们官方群可以一起共建thresh！

👌期待。

**Comment by SeaShrimper** [comment]
预计Q3计划做FFI通信方案
